#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-only
#
# this file is part of SHALLFS
#
# Copyright (c) 2017-2019 Claudio Calvelli <shallfs@gladserv.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see the file COPYING in the distribution).
# If not, see <http://www.gnu.org/licenses/>.

# locate the "shall" sources...
dir="`dirname "$0"`"
[ "x$dir" != x -a \
  -d "$dir/shallfs" -a \
  -d "$dir/include/shallfs" -a \
  -f "$dir/patch" ] || \
    { echo "Cannot find shall sources" >&2; exit 1; }

# copy the fs and include directories
cp -a "$dir/shallfs" fs/
cp -a "$dir/include/shallfs" include/

# and patch the Makefiles
patch -sp1 < "$dir/patch"

