#!/bin/sh

# locate the "shall" sources...
dir="`dirname "$0"`"
[ "x$dir" != x -a \
  -d "$dir/shallfs" -a \
  -d "$dir/include/shallfs" -a \
  -f "$dir/patch" ] || \
    { echo "Cannot find shall sources" >&2; exit 1; }

# copy the fs and include directories
mkdir -p fs/shallfs
ls "$dir/shallfs" | while read name
do
    cmp -s "$dir/shallfs/$name" "fs/shallfs/$name" || \
	cp -a "$dir/shallfs/$name" "fs/shallfs/$name"
done

mkdir -p include/shallfs
ls "$dir/include/shallfs" | while read name
do
    cmp -s "$dir/include/shallfs/$name" "include/shallfs/$name" || \
	cp -a "$dir/include/shallfs/$name" "include/shallfs/$name"
done

